version: "3"
services:
  db:
    image: postgres:13.4
    container_name: postgresql
    ports:
      - 5432:5432
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always